---
name: osgish
version: v0.2.0_1
author:
  - Roland Huss (roland@cpan.org)
abstract: A readline shell for OSGi
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
build_requires:
  File::Copy: 0
  Module::Build: 0.35
  Test: 0
  Test::Deep: 0
  Test::More: 0
requires:
  Carp: 0
  Config::General: 0
  Data::Dumper: 0
  Getopt::Long: 0
  JMX::Jmx4Perl: 0.60
  Pod::Usage: 0
  Term::Clui: 0
  Term::ReadLine: 0
  Term::ReadLine::Perl: 0
  Term::ShellUI: 0.86
recommends:
  Term::ANSIColor: 2.02
  Term::ReadLine::Gnu: 0.27
configure_requires:
  Module::Build: 0.35
provides:
  OSGi::Osgish:
    file: lib/OSGi/Osgish.pm
    version: v0.2.0_1
  OSGi::Osgish::Agent:
    file: lib/OSGi/Osgish/Agent.pm
  OSGi::Osgish::Agent::Upload:
    file: lib/OSGi/Osgish/Agent/Upload.pm
  OSGi::Osgish::Command:
    file: lib/OSGi/Osgish/Command.pm
  OSGi::Osgish::Command::Bundle:
    file: lib/OSGi/Osgish/Command/Bundle.pm
  OSGi::Osgish::Command::Global:
    file: lib/OSGi/Osgish/Command/Global.pm
  OSGi::Osgish::Command::Server:
    file: lib/OSGi/Osgish/Command/Server.pm
  OSGi::Osgish::Command::Service:
    file: lib/OSGi/Osgish/Command/Service.pm
  OSGi::Osgish::Command::Upload:
    file: lib/OSGi/Osgish/Command/Upload.pm
  OSGi::Osgish::CommandHandler:
    file: lib/OSGi/Osgish/CommandHandler.pm
  OSGi::Osgish::CompletionHandler:
    file: lib/OSGi/Osgish/CompletionHandler.pm
  OSGi::Osgish::ServerHandler:
    file: lib/OSGi/Osgish/ServerHandler.pm
  OSGi::Osgish::Shell:
    file: lib/OSGi/Osgish/Shell.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
